### ISSUE TITLE
Change config from yaml to json?

### ISSUE THREAD

**Issue by markgandolfo** [markgandolfo/http-to-sqs#5]
Should we change the config from yaml to json?
I think the current implementaiton of the yaml parser could use some love. Perhaps we don't need the project key, and instead just the path and sqs queue. 

This will simplify the implementation, as we could create an array of Routes instead of nested Structs. 

Below is a sample implementation... Thoughts?

http://stackoverflow.com/questions/16465705/how-to-handle-configuration-in-go

```
{
    "Path": "/api/v1/path1"
     "Sqs": "sqs_queue_1"
}


import (
    "encoding/json"
    "os"
    "fmt"
)

type Route struct {
    Path    string
    Sqs     string
}

file, _ := os.Open("conf.json")
decoder := json.NewDecoder(file)
route := Route{}
err := decoder.Decode(&route)
if err != nil {
  fmt.Println("error:", err)
}
fmt.Println(route.Path)
```

**Comment by fud** [comment]
I think I like json much more than YAML anyway so I'd be happy to go with that.
